# Generated by Django 5.1.6 on 2025-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('icao24', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=8, null=True)),
                ('country', models.CharField(max_length=70)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('velocity', models.FloatField(null=True)),
                ('direction', models.FloatField(null=True)),
                ('category', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('icao24',),
            },
        ),
    ]
