# Generated by Django 5.1.6 on 2025-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_flight_flightmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='callsign',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
